### ISSUE TITLE
Would it be possible to update the PCB so that A6 and A7 can be shorted to B6 and B7 (for USB 2.0 data purposes)

### ISSUE THREAD

**Issue by sabogalc** [ide/usb-c-to-c-power-mod#1]
Hello, I just wanted to say thank you for providing such a useful PCB for modernizing our charging ports.

I like that the 12-pin connector is used here because it also has the necessary connections for Data+ and Data-. While I do not intend to use this port in applications where I want to retain data transfer, I think it would make a useful addition to the project if it were possible.

[Here](https://imgur.com/a/4DTMLal) is a rough pinout I made of the connector. I'm not sure if it's possible to short the USB 2.0 Data pins together without overlapping them, but I do think it would be useful if they could be bridged and then there was a larger pad area to solder to for D+ and D-.

I was inspired to make this feature request by page 7 of [this document](https://www.st.com/content/ccc/resource/technical/document/application_note/group0/93/26/b0/0f/a6/cf/49/bb/DM00294046/files/DM00294046.pdf/jcr:content/translations/en.DM00294046.pdf), which I have screenshotted and attached below.
![image](https://user-images.githubusercontent.com/53708281/162601295-0c245c3c-eed9-4c76-b92b-b85e968c31b5.png)
Additionally, [this Stack Exchange answer](https://electronics.stackexchange.com/a/291427) gave a similar solution.

**Comment by ide** [comment]
Hi, I'm not planning on changing the features of this PCB but maybe I can offer guidance for how to make the changes. The original intent of this PCB was to "patch" a keyboard that already had a USB-C port but was missing the pulldown resistors needed for C-to-C charging. I left the data pins alone since they were working.

I made the PCB using free software called [KiCad](https://www.kicad.org/). I used an older version (v5.1.10) but I suspect v6 will be able to import the project.

You'll need to add four more pads to the PCB for A6/A7/B6/B7. Copying and pasting one of the existing CC pads is probably easiest since it's already the correct dimensions.

OSH Park's flex PCBs support two copper layers. Each layer is like a floor of a building -- the hallways (traces) on one floor (layer) are independent from hallways of another floor (modulo electromagnetic interference, but don't think that is an issue here). Add a small trace from A6 to B6 on the top layer and a small trace from A7 to B7 on the bottom layer. These traces will be covered by solder mask so they don't short other components on the device.

You also mentioned solder pads for the data pins. Add two test pads to the top layer. Add a trace from one of the pads to the A6/B6 trace. For the A7/B7 trace you'll need to add a via, which is like a stairwell between floors, to create a path from the other test pad to the bottom layer where the A7/B7 trace is.

**Comment by sabogalc** [comment]
Awesome, thank you for all of this helpful information. If I do complete this modification, should I make a pull request, or would a fork be more appropriate?

**Comment by ide** [comment]
I'd suggest keeping a separate repo since the intent behind the PCBs is different and I set up this repo more to share my work than maintain it.

**Comment by sabogalc** [comment]
I've never used KiCad before, and this is what I was able to whip up by just copy and pasting some stuff and relocating it.
![image](https://user-images.githubusercontent.com/53708281/164160142-7edaae20-5648-46ec-96f4-9c0670bde73c.png)
I have a feeling I'm doing something wrong, and there is a better way. I tried following some tutorials but I've still got a ways to go before I can successfully achieve this. Could you point me to any relevant tutorials? Thank you.

**Comment by ide** [comment]
That looks roughly right to me. Sorry I don't have any tutorials. I searched online for specific things I wanted to do and learned the parts of KiCad I needed as I went when I was figuring things out. OSH Park shows a preview of the board once you upload the Gerber files, which should give you an idea of whether the board physically looks right.
